<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>ScreenLingo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="tessdata\chi_sim.traineddata" />
    <None Remove="tessdata\chi_tra.traineddata" />
    <None Remove="tessdata\eng.traineddata" />
    <None Remove="tessdata\jpn.traineddata" />
    <None Remove="tessdata\kor.traineddata" />
    <None Remove="tessdata\rus.traineddata" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="tessdata\jpn.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="ScreenLingo.ico" />
    <Content Include="tessdata\chi_sim.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tessdata\chi_tra.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tessdata\eng.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tessdata\kor.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tessdata\rus.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="Fluent.LibreTranslate" Version="1.0.6" />
    <PackageReference Include="GTranslate" Version="2.3.1" />
    <PackageReference Include="LibreTranslate.Net" Version="1.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.9" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="Tesseract.Drawing" Version="5.2.0" />
  </ItemGroup>

</Project>
